### ISSUE TITLE
执行报错中断

### ISSUE THREAD

**Issue by liangjaden** [r0ysue/r0capture#106]
Traceback (most recent call last):
  File "C:\Users\NUC\Downloads\r0capture-2.1\r0capture-2.1\r0capture.py", line 351, in <module>
    ssl_log(int(parsed.process) if parsed.process.isdigit() else parsed.process, parsed.pcap, parsed.verbose, isUsb=parsed.isUsb, isSpawn=parsed.isSpawn, ssllib=parsed.ssl, wait=parsed.wait)
  File "C:\Users\NUC\Downloads\r0capture-2.1\r0capture-2.1\r0capture.py", line 254, in ssl_log
    pid = device.spawn([process])
  File "C:\Users\NUC\AppData\Roaming\Python\Python310\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\NUC\AppData\Roaming\Python\Python310\site-packages\frida\core.py", line 968, in spawn
    return self._impl.spawn(program, **kwargs)
frida.TimedOutError: unexpectedly timed out while waiting for signal from process with PID 19204

**Comment by givemefivw** [comment]
这种方式大概是寄了  尝试了师傅的r0，还有frida-skeleton，现在都没有办法抓了
