### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by qzhuorui** [r0ysue/r0capture#124]
frida 12.8.0
在已经开启frida-server的情况下，运行脚本报错：
python3 D:\js\r0capture\r0capture.py -U -f com.appsflyer.onelink.appsflyeronelinkbasicapp -v

--------------------------------------------------------------------------------------------
           .oooo.                                      .
          d8P'`Y8b                                   .o8
oooo d8b 888    888  .ooooo.   .oooo.   oo.ooooo.  .o888oo oooo  oooo  oooo d8b  .ooooo.
`888""8P 888    888 d88' `"Y8 `P  )88b   888' `88b   888   `888  `888  `888""8P d88' `88b
 888     888    888 888        .oP"888   888   888   888    888   888   888     888ooo888
 888     `88b  d88' 888   .o8 d8(  888   888   888   888 .  888   888   888     888    .o
d888b     `Y8bd8P'  `Y8bod8P' `Y888""8o  888bod8P'   "888"  `V88V"V8P' d888b    `Y8bod8P'
                                         888
                                        o888o
                    https://github.com/r0ysue/r0capture
--------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "D:\js\r0capture\r0capture.py", line 373, in <module>
    wait=parsed.wait
  File "D:\js\r0capture\r0capture.py", line 260, in ssl_log
    pid = device.spawn([process])
  File "D:\pyenv\pyenv-win-master\pyenv-win\versions\3.7.7\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "D:\pyenv\pyenv-win-master\pyenv-win\versions\3.7.7\lib\site-packages\frida\core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.ServerNotRunningError: unable to connect to remote frida-server

**Comment by lihailiang3393** [comment]
你好，解决了吗，我的也是12.8.0,同样的报错
