### ISSUE TITLE
执行最新版本的出现报错

### ISSUE THREAD

**Issue by ygsun** [r0ysue/r0capture#37]
Traceback (most recent call last):
  File "D:/Projects/work/frida_project/r0capture/r0capture.py", line 351, in <module>
    ssl_log(int(parsed.process) if parsed.process.isdigit() else parsed.process, parsed.pcap, parsed.verbose, isUsb=parsed.isUsb, isSpawn=parsed.isSpawn, ssllib=parsed.ssl, wait=parsed.wait)
  File "D:/Projects/work/frida_project/r0capture/r0capture.py", line 288, in ssl_log
    script = session.create_script(_FRIDA_SCRIPT)
  File "C:\Users\Vincent\Anaconda3\envs\frida\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Vincent\Anaconda3\envs\frida\lib\site-packages\frida\core.py", line 204, in create_script
    return Script(self._impl.create_script(*args, **kwargs))
frida.InvalidArgumentError: script(line 195): SyntaxError: function statement not allowed

**Comment by r0ysue** [comment]
已修复
