### ISSUE TITLE
help

### ISSUE THREAD

**Issue by KeparYTbcc** [r0ysue/r0capture#48]
Traceback (most recent call last):
  File "/root/r0capture/r0capture.py", line 356, in <module>
    ssl_log(
  File "/root/r0capture/r0capture.py", line 257, in ssl_log
    pid = device.spawn([process])
  File "/usr/local/lib/python3.9/dist-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/frida/core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.ServerNotRunningError: unable to connect to remote frida-server

**Comment by r0ysue** [comment]
please running your frida-server first ~~
