### ISSUE TITLE
NameError: name 'hexdump' is not defined 

### ISSUE THREAD

**Issue by 03128crz** [r0ysue/r0capture#52]
运行：报错，且没有导出客户端证书，（App已添加存储权限）
python r0capture.py -H 192.168.50.153:8888 -f xxx.xxx.xxx.xxx -v

NameError: name 'hexdump' is not defined
SSL Session: 71A92366608A0A253692FADF47DCC8377D374F83C20B8B7C345E360D9D3272BB
[SSL_read] 120.83.147.111:443 --> 192.168.50.153:37088
Traceback (most recent call last):
  File "/root/miniconda3/envs/py380/lib/python3.8/site-packages/frida/core.py", line 383, in _on_message
    callback(message, data)
  File "r0capture.py", line 239, in on_message
    hexdump.hexdump(data)
NameError: name 'hexdump' is not defined
SSL Session: 71A92366608A0A253692FADF47DCC8377D374F83C20B8B7C345E360D9D3272BB
[SSL_read] 120.83.147.111:443 --> 192.168.50.153:37088

Traceback (most recent call last):
  File "/root/miniconda3/envs/py380/lib/python3.8/site-packages/frida/core.py", line 383, in _on_message
    callback(message, data)
  File "r0capture.py", line 239, in on_message
    hexdump.hexdump(data)
NameError: name 'hexdump' is not defined
SSL Session: 71A92366608A0A253692FADF47DCC8377D374F83C20B8B7C345E360D9D3272BB
[SSL_read] 120.83.147.111:443 --> 192.168.50.153:37088
Traceback (most recent call last):
  File "/root/miniconda3/envs/py380/lib/python3.8/site-packages/frida/core.py", line 383, in _on_message
    callback(message, data)
  File "r0capture.py", line 239, in on_message
    hexdump.hexdump(data)
NameError: name 'hexdump' is not defined
SSL Session: 71A92366608A0A253692FADF47DCC8377D374F83C20B8B7C345E360D9D3272BB
[SSL_read] 120.83.147.111:443 --> 192.168.50.153:37088
Traceback (most recent call last):
  File "/root/miniconda3/envs/py380/lib/python3.8/site-packages/frida/core.py", line 383, in _on_message
    callback(message, data)
  File "r0capture.py", line 239, in on_message
    hexdump.hexdump(data)
NameError: name 'hexdump' is not defined
^CYou have stoped logging.
^C^C^C^C^CYou have stoped logging.

**Comment by dwaynewei** [comment]
> @03128crz 楼主 遇到跟这个issue一样的问题。 请问你解决了吗？ 是怎么解决的想请教一下，谢谢！

> 解决了，哈哈。  原来是要安装一下这个依赖。  `pip3 install hexdump` 就可以了 。
