### ISSUE TITLE
NameError: name 'hexdump' is not defined

### ISSUE THREAD

**Issue by tiefeiniu** [r0ysue/r0capture#54]
Traceback (most recent call last):
  File "D:\python\lib\site-packages\frida\core.py", line 383, in _on_message
    callback(message, data)
  File "D:\javaby\gongju\r0capture\r0capture.py", line 239, in on_message
    hexdump.hexdump(data)
NameError: name 'hexdump' is not defined
SSL Session: 833A98DD38DCA4E3FAA733B177DE922A6B10A0958B473301799FA91CAEF1ACF3
[SSL_read] 115.159.231.144:443 --> 172.16.1.15:54395
Traceback (most recent call last):
  File "D:\python\lib\site-packages\frida\core.py", line 383, in _on_message
    callback(message, data)
  File "D:\javaby\gongju\r0capture\r0capture.py", line 239, in on_message
    hexdump.hexdump(data)
NameError: name 'hexdump' is not defined
SSL Session: B5FEB6A8BFF0EDC0B2C09F0DC545B9A217E1DC4A95790CA1A4DB932EE3D859B0
[SSL_read] 123.206.235.144:443 --> 172.16.1.15:47914
Traceback (most recent call last):
  File "D:\python\lib\site-packages\frida\core.py", line 383, in _on_message
    callback(message, data)
  File "D:\javaby\gongju\r0capture\r0capture.py", line 239, in on_message
    hexdump.hexdump(data)
NameError: name 'hexdump' is not defined
SSL Session: D4E416C3AE4F321FFA8196616BC8C251E7E3954DCD3D200138309E67CCA1DFF5
[SSL_read] 123.206.235.145:443 --> 172.16.1.15:34207
Traceback (most recent call last):
  File "D:\python\lib\site-packages\frida\core.py", line 383, in _on_message
    callback(message, data)
  File "D:\javaby\gongju\r0capture\r0capture.py", line 239, in on_message
    hexdump.hexdump(data)
NameError: name 'hexdump' is not defined
SSL Session: DD9542DD18D63C80C062E26EC2673A637E9B085103A342B444166EC196021C89
[SSL_read] 123.206.235.144:443 --> 172.16.1.15:47912
Traceback (most recent call last):
  File "D:\python\lib\site-packages\frida\core.py", line 383, in _on_message
    callback(message, data)
  File "D:\javaby\gongju\r0capture\r0capture.py", line 239, in on_message
    hexdump.hexdump(data)
NameError: name 'hexdump' is not defined
SSL Session:
[HTTP_send] 172.16.1.15:33222 --> 14.22.7.140:80
Traceback (most recent call last):
  File "D:\python\lib\site-packages\frida\core.py", line 383, in _on_message
    callback(message, data)
  File "D:\javaby\gongju\r0capture\r0capture.py", line 239, in on_message
    hexdump.hexdump(data)
NameError: name 'hexdump' is not defined
SSL Session:
[HTTP_recv] 14.22.7.140:80 --> 172.16.1.15:33222
Traceback (most recent call last):
  File "D:\python\lib\site-packages\frida\core.py", line 383, in _on_message
    callback(message, data)
  File "D:\javaby\gongju\r0capture\r0capture.py", line 239, in on_message
    hexdump.hexdump(data)
NameError: name 'hexdump' is not defined

**Comment by tiefeiniu** [comment]
这是什么错误呢？

**Comment by r0ysue** [comment]
pip install hexdump
