### ISSUE TITLE
最新版执行出错

### ISSUE THREAD

**Issue by Lockey-J** [r0ysue/r0capture#64]
D:\Programs\Python\Python38>python G:\VSCode\r0capture\r0capture.py -U com.shangxueba.newsxb -v -p shangxueba.pcap

--------------------------------------------------------------------------------------------
           .oooo.                                      .
          d8P'`Y8b                                   .o8
oooo d8b 888    888  .ooooo.   .oooo.   oo.ooooo.  .o888oo oooo  oooo  oooo d8b  .ooooo.
`888""8P 888    888 d88' `"Y8 `P  )88b   888' `88b   888   `888  `888  `888""8P d88' `88b
 888     888    888 888        .oP"888   888   888   888    888   888   888     888ooo888
 888     `88b  d88' 888   .o8 d8(  888   888   888   888 .  888   888   888     888    .o
d888b     `Y8bd8P'  `Y8bod8P' `Y888""8o  888bod8P'   "888"  `V88V"V8P' d888b    `Y8bod8P'
                                         888
                                        o888o                                                                           
                    https://github.com/r0ysue/r0capture
--------------------------------------------------------------------------------------------

attach
Traceback (most recent call last):
  File "G:\VSCode\r0capture\r0capture.py", line 357, in <module>
    ssl_log(
  File "G:\VSCode\r0capture\r0capture.py", line 265, in ssl_log
    session = device.attach(process)
  File "D:\Programs\Python\Python38\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "D:\Programs\Python\Python38\lib\site-packages\frida\core.py", line 156, in attach
    return Session(self._impl.attach(self._pid_of(target), *args, **kwargs))
  File "D:\Programs\Python\Python38\lib\site-packages\frida\core.py", line 180, in _pid_of
    return self.get_process(target).pid
  File "D:\Programs\Python\Python38\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "D:\Programs\Python\Python38\lib\site-packages\frida\core.py", line 112, in get_process
    raise _frida.ProcessNotFoundError("unable to find process with name '%s'" % process_name)
frida.ProcessNotFoundError: unable to find process with name 'com.shangxueba.newsxb'

D:\Programs\Python\Python38>

真机 magisk root 安卓10

**Comment by r0ysue** [comment]
unable to find process with name 'com.shangxueba.newsxb' 没有这个进程
