### ISSUE TITLE
输出出错

### ISSUE THREAD

**Issue by ccnie** [r0ysue/r0capture#70]
环境：
小米 MIX
android 8

python r0capture.py -U -f com.android.browser -v

java.lang.Throwable
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:114)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:139)
        at i.q.read(SourceFile:4)
        at i.b.read(SourceFile:2)
        at i.x.read(SourceFile:3)
        at okhttp3.internal.http1.Http1Codec$AbstractSource.read(SourceFile:1)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(SourceFile:3)
        at i.w.read(SourceFile:9)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.bumptech.glide.util.ContentLengthInputStream.read(SourceFile:5)
        at com.bumptech.glide.util.ContentLengthInputStream.read(SourceFile:4)
        at com.bumptech.glide.load.model.StreamEncoder.encode(SourceFile:4)
        at com.bumptech.glide.load.model.StreamEncoder.encode(SourceFile:1)
        at com.bumptech.glide.load.engine.DataCacheWriter.write(SourceFile:1)
        at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.put(SourceFile:10)
        at com.bumptech.glide.load.engine.SourceGenerator.cacheData(SourceFile:6)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceFile:3)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(SourceFile:4)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(SourceFile:4)
        at com.bumptech.glide.load.engine.DecodeJob.run(SourceFile:7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(SourceFile:6)

**Comment by r0ysue** [comment]
这是功能，不是异常。
