### ISSUE TITLE
spawn 模式无法使用 PID，attach 模式通过 PID 无法抓到数据

### ISSUE THREAD

**Issue by sheng-di** [r0ysue/r0capture#77]
前提：这是一个多进程应用，但是可以看到 PID:
![image](https://user-images.githubusercontent.com/13643746/152010196-92c50bec-dfbf-4c62-8fd0-33d2ed5e0f6c.png)

## spawn 模式
命令：
```bash
python .\r0capture.py -U -f -v 14823
```
输出：
有报错信息，提示 PID 不能是 int
```
Traceback (most recent call last):
  File "C:\Users\sheng\Downloads\r0capture-main\r0capture.py", line 365, in <module>
    ssl_log(
  File "C:\Users\sheng\Downloads\r0capture-main\r0capture.py", line 261, in ssl_log
    pid = device.spawn([process])
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python310\lib\site-packages\frida-15.1.15-py3.10-win-amd64.egg\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python310\lib\site-packages\frida-15.1.15-py3.10-win-amd64.egg\frida\core.py", line 149, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
TypeError: argument 1 must be str, not int
```
## attach 模式
命令：
```bash
python r0capture.py -U 14823 -v -p camera.pcap
```
输出：
无异常报错，但是生成的 pcap 文件只有 1kb，打开后没有任何内容。

**Comment by r0ysue** [comment]
spawn模式还是使用包名叭
