### ISSUE TITLE
attach模式会找不到包名

### ISSUE THREAD

**Issue by marykeil** [r0ysue/r0capture#81]
硬件环境小米5s，已经root。安卓版本8.0.0，miui版本miui10 9.8.29，开发版本
attach模式会如果app打开了，大概率提示不能找到包名，如果没有打开软件，偶尔可以运行正常。
Spawn 模式可以抓数据正常，不会提示找不到包名的情况。
frida-ps -U可以看到包名

attach错误提示如下
Traceback (most recent call last):
  File "D:\embed\unpack\r0capture-main\r0capture.py", line 366, in <module>
    ssl_log(
  File "D:\embed\unpack\r0capture-main\r0capture.py", line 267, in ssl_log
    session = device.attach(process)
  File "D:\programusr\Python310\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "D:\programusr\Python310\lib\site-packages\frida\core.py", line 165, in attach
    return Session(self._impl.attach(self._pid_of(target), *args, **kwargs))
  File "D:\programusr\Python310\lib\site-packages\frida\core.py", line 193, in _pid_of
    return self.get_process(target).pid
  File "D:\programusr\Python310\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "D:\programusr\Python310\lib\site-packages\frida\core.py", line 121, in get_process
    raise _frida.ProcessNotFoundError("unable to find process with name '%s'" % process_name)
frida.ProcessNotFoundError: unable to find process with name 'com.tencent.mobileqq'

**Comment by marykeil** [comment]
安卓版本8.0.0
miui版本miui10 9.8.29

**Comment by r0ysue** [comment]
不大清楚。。。
可能是frida自己的bug，换个版本试试呢？
