### ISSUE TITLE
frida-server使用非标准端口后，r0capture连不上

### ISSUE THREAD

**Issue by RiverChu0** [r0ysue/r0capture#87]
启动`frida-server`：
```shell
/data/local/tmp/frida-server -l 0.0.0.0:17890
```
frida-ps能列出进程：
```shell
frida-ps -H 192.168.0.112:17890
```

r0capture无法连接：
```shell
python r0capture.py -H 192.168.0.112:17890 -U 5814 -p aaa.pcap
```

报错：
```shell
--------------------------------------------------------------------------------------------
           .oooo.                                      .
          d8P'`Y8b                                   .o8
oooo d8b 888    888  .ooooo.   .oooo.   oo.ooooo.  .o888oo oooo  oooo  oooo d8b  .ooooo.
`888""8P 888    888 d88' `"Y8 `P  )88b   888' `88b   888   `888  `888  `888""8P d88' `88b
 888     888    888 888        .oP"888   888   888   888    888   888   888     888ooo888
 888     `88b  d88' 888   .o8 d8(  888   888   888   888 .  888   888   888     888    .o
d888b     `Y8bd8P'  `Y8bod8P' `Y888""8o  888bod8P'   "888"  `V88V"V8P' d888b    `Y8bod8P'
                                         888
                                        o888o                                                                           
                    https://github.com/r0ysue/r0capture
--------------------------------------------------------------------------------------------

attach
Traceback (most recent call last):
  File "D:\xx\xx\xx\r0capture\r0capture.py", line 365, in <module>
    ssl_log(
  File "D:\xx\xx\xx\r0capture\r0capture.py", line 267, in ssl_log
    session = device.attach(process)
  File "D:\xx\xx\xx\Python\Python39\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "D:\xx\xx\xx\Python\Python39\lib\site-packages\frida\core.py", line 165, in attach
    return Session(self._impl.attach(self._pid_of(target), *args, **kwargs))
frida.ServerNotRunningError: unable to connect to remote frida-server: closed
```

电脑端windows。如果不以非标准端口运行，则可以连接上。如果以标准端口运行了，-H 随便填IP端口都能连上，感觉-H参数不起作用

r0capture版本15.1.22

**Comment by r0ysue** [comment]
-H 和 -U 不可以同时在一个命令里
