### ISSUE TITLE
Instragram无法抓包

### ISSUE THREAD

**Issue by esingtse** [r0ysue/r0capture#9]
```
Package        Version
-------------- -------
colorama       0.4.4
frida          14.1.2
frida-tools    9.0.1
hexdump        3.3
pip            18.1
prompt-toolkit 3.0.8
Pygments       2.7.2
setuptools     40.6.2
wcwidth        0.2.5
```

```Error.log
--------------------------------------------------------------------------------------------
           .oooo.                                      .
          d8P'`Y8b                                   .o8
oooo d8b 888    888  .ooooo.   .oooo.   oo.ooooo.  .o888oo oooo  oooo  oooo d8b  .ooooo.
`888""8P 888    888 d88' `"Y8 `P  )88b   888' `88b   888   `888  `888  `888""8P d88' `88b
 888     888    888 888        .oP"888   888   888   888    888   888   888     888ooo888
 888     `88b  d88' 888   .o8 d8(  888   888   888   888 .  888   888   888     888    .o
d888b     `Y8bd8P'  `Y8bod8P' `Y888""8o  888bod8P'   "888"  `V88V"V8P' d888b    `Y8bod8P'
                                         888
                                        o888o
                    https://github.com/r0ysue/r0capture
--------------------------------------------------------------------------------------------

attach
Traceback (most recent call last):
  File "r0capture.py", line 346, in <module>
    ssl_log(int(parsed.process) if parsed.process.isdigit() else parsed.process, parsed.pcap, parsed.verbose, isUsb=parsed.isUsb, isSpawn=parsed.isSpawn, ssllib=parsed.ssl, wait=parsed.wait)
  File "r0capture.py", line 256, in ssl_log
    session = device.attach(process)
  File "/Users/esingtse/.pyenv/versions/frida/lib/python3.6/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/Users/esingtse/.pyenv/versions/frida/lib/python3.6/site-packages/frida/core.py", line 156, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.TransportError: the connection is closed
```

Instrgram在抓包开始前运行`python r0capture.py -U com.instagram.android -p ins.pcap`，程序会直接闪退，重新打开程序的时候报错

**Comment by r0ysue** [comment]
这还是环境问题
按照这个教程设置好环境：
https://github.com/r0ysue/AndroidSecurityStudy/blob/master/FRIDA/A01/README.md

**Comment by esingtse** [comment]
我目前的本地环境是Pixel Android 8.1
Magisk V20.4
抖音、微博都可以正常抓包，Instagram却不行。

**Comment by r0ysue** [comment]
报错：the connection is closed
就是环境问题 ~ 
可以把spawn和attach模式都尝试一下~

**Comment by ganbiedetuzi** [comment]
错啦，这是反调试
