### ISSUE TITLE
SSL在高版本上的实现机制有区别

### ISSUE THREAD

**Issue by ZipperCode** [r0ysue/r0capture#98]
脚本判断了大于安卓8的时候，hook的类是 `com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream`
本人安卓12  + 红米k30 pro 根据堆栈发现的类是: `com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream`
堆栈如下：
```
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
at java.net.SocketInputStream.read(SocketInputStream.java:176)
at java.net.SocketInputStream.read(SocketInputStream.java:144)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(Native Method)
at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
at com.inmobi.media.gv.b(NetworkConnection.java:169)
at com.inmobi.media.gv.a(NetworkConnection.java:75)
at com.inmobi.media.ha.a(SyncNetworkTask.java:18)
at com.inmobi.media.fw.a(ConfigNetworkClient.java:134)
at com.inmobi.media.fw.run(ConfigNetworkClient.java:3037)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:920)

```

**Comment by androiddan** [comment]
怎么解决，android11，小米11青春版一样的问题
java.lang.Throwable
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.write(Native Method)
	at com.android.okhttp.okio.Okio$1.write(Okio.java:78)
	at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:157)
	at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:222)
	at com.android.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:163)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:748)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
	at com.umeng.commonsdk.statistics.internal.c.a(NetworkHelper.java:500)
	at com.umeng.commonsdk.statistics.internal.c.a(NetworkHelper.java:294)
	at com.umeng.commonsdk.statistics.c.a(NetWorkManager.java:170)
	at com.umeng.commonsdk.framework.a.r(UMNetWorkSender.java:563)
	at com.umeng.commonsdk.framework.a.k(UMNetWorkSender.java:35)
	at com.umeng.commonsdk.framework.a$2.handleMessage(UMNetWorkSender.java:311)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by tcc0lin** [comment]
> 同问，解决了吗？

here：[https://github.com/tcc0lin/FridaPlayground/blob/main/modules/ssl/hook_ssl_java.ts](url)
